version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    funlen:
      lines: 110
      statements: 50
    lll:
      line-length: 120
    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "10"
        - "64"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: exporter_test.go
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
      - path: exporter_test.go
        text: make it a constant
      - path: main.go
        text: 'G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jwkohnen/conntrack-stats-exporter
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
