linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    # - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    # - gochecknoglobals
    # - gocognit
    - godot
    # - godox
    # - goerr113
    # - nestif
    - testpackage
    - revive
    - wsl
    - mnd

linters-settings:
  lll:
    line-length: 120
  funlen:
    lines: 110
    statements: 50
  goimports:
    local-prefixes: github.com/jwkohnen/conntrack-stats-exporter
  mnd:
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '10'
      - '64'

issues:
  exclude-rules:
    - path: exporter_test.go
      text: "G306: Expect WriteFile permissions to be 0600 or less"
    - path: exporter_test.go
      text: "make it a constant"
    - path: main.go
      text: "G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server"
