FROM	golang:1.19.1 as build
WORKDIR	/conntrack-stats-exporter
COPY	go.mod go.sum ./
RUN	go mod download
COPY	*.go ./
COPY	exporter exporter
RUN	go mod verify
RUN	go build --race -o conntrack-stats-exporter

FROM	debian:stable-slim
RUN	apt-get update
RUN	apt-get -qy install conntrack iproute2
COPY	--from=build /conntrack-stats-exporter/conntrack-stats-exporter /usr/local/sbin/
ENTRYPOINT	[ "/usr/local/sbin/conntrack-stats-exporter" ]
